### ISSUE TITLE
Add id for content element

### ISSUE THREAD

**Issue by szpajsi** [TYPO3-Headless/nuxt-typo3#163]
Adding default id (from API) for all content elements. Maybe it can be add to _CeFrame_ (Content element wrapper - Section Frame). It would be helpful for using anchor links.

**Comment by gdulamat** [comment]
Great idea, but we have to keep in mind that `T3Frame` (old `CeFrame`) is an optional component in your app structure. When nuxt-typo3 loop through content elements array the `T3Frame` or `T3Dynamic` are rendered conditionally. So we are not sure if the frame will be rendered.

I recommend to bind component id as html attribute to the frame if it exist, otherwise to the content element itself.

**Comment by mercs600** [comment]
@gdulamat it makes sense. The best place to put the code will be T3Renderer.js - we can bind id attribute there to t3dynamic or t3frame
