### ISSUE TITLE
Documentation and or Bug: Wrong path for import type

### ISSUE THREAD

**Issue by daUhradone** [TYPO3-Headless/nuxt-typo3#334]
at: Documentation-> Layouts:

`import { T3BackendLayout } from '@t3headless/nuxt-typo3'`

The path goes to '/modules' and the type is not imported.
I had to do a full path to '/types' to make it work.

`'/home/thomas/CODE/Nuxt/nuxt-typo3/node_modules/@t3headless/nuxt-typo3/dist/types'`

module.d.mts also exports the types but they are not recognized on import, TypeScript gives an error

The nuxt-typo3 module itself also uses '../../types' for its type imports.

**Comment by mercs600** [comment]
We have released new version 2.0.2, due to changes in Nuxt 3.10.x. 
Now it should work. 

We have also updated documentation to clarify that types should be imported with the `type` keyword:
`import type { T3BackendLayout } from '@t3headless/nuxt-typo3'`

Feel free to reopen this issue if you have any questions.
